version: '3.9'

services:
  database:
    image: mysql
    container_name: menuapp_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'menuapp_db'
    ports:
      - '3306:3306'
